// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApoiwyGII2gcD77E87VZ0uLwSdoWQwJuM',
    appId: '1:759537182148:web:3a613d653babb02932b091',
    messagingSenderId: '759537182148',
    projectId: 'capstone-6653b',
    authDomain: 'capstone-6653b.firebaseapp.com',
    storageBucket: 'capstone-6653b.appspot.com',
    measurementId: 'G-96GRCDX935',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuIUGikX_CABd8ieB1vieFuOj_24cv_5s',
    appId: '1:759537182148:android:7e68d09f0b92b78632b091',
    messagingSenderId: '759537182148',
    projectId: 'capstone-6653b',
    storageBucket: 'capstone-6653b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKcEpbCeeTuhv_DEolaHeMRvgD_BU5Te0',
    appId: '1:759537182148:ios:7244ffde0df813a432b091',
    messagingSenderId: '759537182148',
    projectId: 'capstone-6653b',
    storageBucket: 'capstone-6653b.appspot.com',
    iosClientId: '759537182148-eo4929vaorfrkbqrsqopijiir8bfm00p.apps.googleusercontent.com',
    iosBundleId: 'com.example.stylingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKcEpbCeeTuhv_DEolaHeMRvgD_BU5Te0',
    appId: '1:759537182148:ios:3990cf920a2456ca32b091',
    messagingSenderId: '759537182148',
    projectId: 'capstone-6653b',
    storageBucket: 'capstone-6653b.appspot.com',
    iosClientId: '759537182148-eo3u87vo0e6vtbjucdpdc0p50edrqqev.apps.googleusercontent.com',
    iosBundleId: 'com.example.stylingApp.RunnerTests',
  );
}
